# Site setings
name: 'Stuart Grassie: TemporalCohesion'
title: 'Stuart Grassie: TemporalCohesion'
tagline: "A blog about software development"
description: 'A blog about software development, by Stuart Grassie'
meta_description: 'A blog about software development'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  twitter: stugrassie
  image: 'me1280x.jpg'
  greetings: "Welcome! My name is Stuart Grassie. I'm a software developer based in the North West of England. Itâ€™s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://temporalcohesion.co.uk
disqus: 'temporalcohesion'
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics: UA-9870754-1

# Contact form setings
email: sgrassie@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 
   username: 'stugrassie'
   card: summary
facebook: 'sgrassie'
github: 'sgrassie'
codepen: 
dribbble: 
medium: 
instagram: 
pinterest: 
linkedin: 'sgrassie'
producthunt: 
quora: 

social:
  name: Stuart Grassie
  links:
    - https://twitter.com/stugrassie
    - https://www.facebook.com/sgrassie
    - https://www.linkedin.com/in/sgrassie
    - https://github.com/sgrassie

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title

# Other
markdown: kramdown
highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed
